from . import wujia_franchise_management
from . import wujia_franchise_member
from . import wujia_franchise_inspection_template
from . import wujia_franchise_inspection_template_line
from . import wujia_franchise_inspection
from . import wujia_franchise_inspection_line
from . import wujia_franchise_inspection_question
from . import wujia_franchise_inspection_exam_line
from . import wujia_franchise_inspection_category
from . import wujia_franchise_inspection_ranking
from . import res_partner
from . import res_users
