from . import test_home_c7
from . import test_franchise_switch_f1
from . import test_f5_menu_ownership
from . import test_f5_nav_item
from . import test_scan_f4_overrides
from . import test_scan_e2_status_badge
from . import test_scan_e2b_status_badge
from . import test_home_kpi_e1
from . import test_scan_c8_section_header
from . import test_scan_e4_filter_bar
from . import test_scan_e3_pagination
from . import test_scan_d3_card_header
from . import test_handover_inspection
from . import test_scan_d4_surface_card
from . import test_scan_d5_data_list
