{
    'name': 'Wujia Portal — Return Request',
    'version': '19.0.2.1.0',
    'category': 'Wujia',
    'summary': 'Bù hàng / đổi trả — portal single-product + backend admin + workflow',
    'author': 'WujiaTea',
    'license': 'LGPL-3',
    'depends': ['wujia_sale', 'wujia_portal_base', 'wujia_franchise'],
    'data': [
        'security/wujia_return_groups.xml',
        'security/ir.model.access.csv',
        'security/wujia_return_rules.xml',
        'data/ir_sequence_data.xml',
        'data/return_issue_type_data.xml',
        'views/backend_return_request_views.xml',
        'wizards/compensation_process_wizard_views.xml',
        'views/backend_return_issue_type_views.xml',
        'views/backend_product_views.xml',
        'views/backend_menu.xml',
        'views/sidenav_inherit.xml',
        'views/portal_return_list.xml',
        'views/portal_return_form.xml',
        'views/portal_return_detail.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'wujia_portal_return/static/src/css/portal_return.css',
            'wujia_portal_return/static/src/js/portal_return.js',
        ],
    },
    'installable': True,
    'application': False,
    'auto_install': False,
}
