{
    'name': 'Wujia Franchise',
    'version': '19.0.2.0.1',
    'category': 'Wujia',
    'summary': 'Quản lý cửa hàng nhượng quyền + membership user portal',
    'author': 'WujiaTea',
    'description': """Module quản lý nhượng quyền của Wujia Tea. Bao gồm hồ sơ cửa hàng, membership portal, giám sát cửa hàng, báo cáo và cấu hình giám sát.""",
    'license': 'LGPL-3',
    'depends': [
        'wujia_core',
        'contacts',
        'portal',
        'mail',
        'calendar',
    ],
    'data': [
        'security/wujia_franchise_groups.xml',
        'security/ir.model.access.csv',
        'security/wujia_franchise_rules.xml',
        'views/wujia_franchise_management_views.xml',
        'views/wujia_franchise_member_views.xml',
        'views/wujia_franchise_inspection_views.xml',
        'views/wujia_franchise_inspection_extra_views.xml',
        'views/wujia_franchise_inspection_template_view.xml',
        'views/wujia_franchise_inspection_template_line_view.xml',
        'views/wujia_franchise_inspection_category_view.xml',
        'views/wujia_franchise_inspection_schedule_views.xml',
        'views/wujia_franchise_early_actions.xml',
        
        'views/res_partner_views.xml',
        'views/res_users_views.xml',
        'views/wujia_franchise_menu.xml',
        'data/ir_sequence_data.xml',
        'data/ir_cron_data.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'wujia_franchise/static/src/scss/inspection_schedule.scss',
            'wujia_franchise/static/src/js/inspection_schedule.js',
            'wujia_franchise/static/src/xml/inspection_schedule.xml',
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
}
