# -*- coding: utf-8 -*-
# Copyright (C) NexGen Solutions
{
    'name': 'AI Dynamic Dashboard & KPI Builder',
    'version': '19.0.1.0.5',
    'category': 'Productivity',
    'summary': (
        'Dynamic dashboard builder for Odoo: interactive charts, KPIs, filters, '
        'drill-down, multi-source data and optional AI generation.'
    ),
    'description': """
Dynamic Dashboard AI for Odoo 19
================================

Build interactive business dashboards inside Odoo 19
(Community, Enterprise and Odoo.sh) with a no-code dynamic dashboard builder.

Key features
------------
* Drag-and-drop dynamic dashboard layouts with themes
* 50+ visualization types (tiles, KPIs, charts, maps, lists, embeds and more)
* Optional AI dashboard and chart/item generator (bring your own API key)
* Data from Odoo models, Custom SQL, Visual Query Builder, Excel/CSV,
  Google Sheets, APIs and external databases
* Hierarchical KPIs, filters, drill-down, multi-company and multi-currency
* TV Mode, Present Mode, share links and PNG/PDF/Excel/CSV export
* Ready-made demo galleries for chart types and business apps

Build powerful Odoo dashboards with AI, KPIs, charts, SQL, Visual Query Builder, Excel/CSV data, filters and drill-downs. Create interactive dashboards for Sales, CRM, Accounting, Inventory, Manufacturing, HR and more.

External services
-----------------
* Optional AI features require your own account/API key with the chosen provider
  (OpenAI, Google Gemini, Anthropic Claude or compatible endpoints).
* Core dashboards, charts, SQL, filters, KPIs, TV Mode and sharing work without AI.
""",


    'author': 'NexGen Solutions',
    'website': 'https://nexgensolutions.odoo.com',
    'maintainer': 'NexGen Solutions',
    'support': 'nexgensolutionsodoo@gmail.com',
    'license': 'OPL-1',
    'price': 0.0,
    'currency': 'USD',
    'depends': ['base', 'bus', 'mail', 'web'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'views/ai_wizard_views.xml',
        'views/import_wizard_views.xml',
        'views/move_wizard_views.xml',
        'views/res_config_settings_views.xml',
        'views/dashboard_connection_views.xml',
        'views/dashboard_analysis_views.xml',
        'views/dashboard_mart_views.xml',
        'views/dashboard_kpi_views.xml',
        'views/dashboard_category_views.xml',
        'views/dashboard_views.xml',
        'views/dashboard_item_views.xml',
        'views/dashboard_number_system_views.xml',
        'views/dashboard_date_filter_views.xml',
        'views/demo_record_views.xml',
        'data/cron.xml',
        'data/dashboard_categories.xml',
        'data/dashboard_date_filters.xml',
        'data/dashboard_number_systems.xml',
        'views/menu.xml',
    ],
    'demo': [
        'demo/default_dashboards.xml',
        'demo/demo_chart_types.xml',
        'demo/demo_analysis_templates.xml',
        'demo/demo_seed.xml',
        'demo/demo.xml',
        'demo/demo_menus.xml',
    ],
    'images': [
        'static/description/main_screenshot.gif',
        'static/description/main_screenshot.png',
        'static/description/main_screen_demo.gif',
        'static/description/banner.png',
        'static/description/services/odoo_services.png',
        'static/description/banner.gif',
        'static/description/ai_demo.gif',
        'static/description/ai/ai_input.png',
        'static/description/ai/ai_insights.png',
        'static/description/ai/ai_modes.png',
        'static/description/ai/ai_preview.png',
        'static/description/ai/ai_result.png',
        'static/description/ai/ai_steps.png',
        'static/description/feature_overview.png',
        'static/description/feature_ai.png',
        'static/description/feature_builder.png',
        'static/description/feature_charts.png',
        'static/description/feature_filters.png',
        'static/description/feature_sources.png',
        'static/description/feature_kpi.png',
        'static/description/feature_tv.png',
        'static/description/sql/custom_sql.png',
        'static/description/sql/sql_examples.png',
        'static/description/sql/sql_to_chart.png',
        'static/description/sql/sql_vqb_demo.gif',
        'static/description/sql/visual_query_builder.png',
        'static/description/more/analyses.png',
        'static/description/more/collab_live.png',
        'static/description/more/connectors.png',
        'static/description/more/data_power.png',
        'static/description/more/embeds_tv.png',
        'static/description/more/filters_actions.png',
        'static/description/more/kpi_advanced.png',
        'static/description/examples/crm_dashboard.png',
        'static/description/examples/hr_dashboard.png',
        'static/description/examples/project_dashboard.png',
        'static/description/features/actions.png',
        'static/description/features/analyses.png',
        'static/description/features/bus.png',
        'static/description/features/chat.png',
        'static/description/features/databases.png',
        'static/description/features/embeds.png',
        'static/description/features/filter_widgets.png',
        'static/description/features/formulas.png',
        'static/description/features/multiseries.png',
        'static/description/features/mview.png',
        'static/description/features/python_mart.png',
        'static/description/features/quickedit.png',
        'static/description/features/scrape.png',
        'static/description/features/switchlayout.png',
        'static/description/features/targets.png',
        'static/description/examples/account_dashboard.png',
        'static/description/examples/inventory_dashboard.png',
        'static/description/examples/purchase_dashboard.png',
        'static/description/examples/sales_dashboard.png',
        'static/description/themes/card_themes.png',
        'static/description/themes/chart_themes.png',
        'static/description/themes/theme_dashboard.png',
        'static/description/themes/themes_demo.gif',
        'static/description/export/export_dashboard.png',
        'static/description/export/export_formats.png',
        'static/description/export/export_share_demo.gif',
        'static/description/export/share_email.png',
        'static/description/icon.png',
        'static/description/charts/arcDiagram.png',
        'static/description/charts/area.png',
        'static/description/charts/bar.png',
        'static/description/charts/barLine.png',
        'static/description/charts/bullet.png',
        'static/description/charts/candlestick.png',
        'static/description/charts/chord.png',
        'static/description/charts/chordDirected.png',
        'static/description/charts/chordNonRibbon.png',
        'static/description/charts/doughnut.png',
        'static/description/charts/flower.png',
        'static/description/charts/forceDirected.png',
        'static/description/charts/funnel.png',
        'static/description/charts/gauge.png',
        'static/description/charts/heatmap.png',
        'static/description/charts/horizontalBar.png',
        'static/description/charts/iframe.png',
        'static/description/charts/kpi.png',
        'static/description/charts/line.png',
        'static/description/charts/list.png',
        'static/description/charts/map.png',
        'static/description/charts/mapPoints.png',
        'static/description/charts/matrixHeatmap.png',
        'static/description/charts/odoo_view.png',
        'static/description/charts/ohlc.png',
        'static/description/charts/pack.png',
        'static/description/charts/partition.png',
        'static/description/charts/pictorial.png',
        'static/description/charts/pie.png',
        'static/description/charts/polarArea.png',
        'static/description/charts/pyramid.png',
        'static/description/charts/radar.png',
        'static/description/charts/radialBar.png',
        'static/description/charts/sankey.png',
        'static/description/charts/scatter.png',
        'static/description/charts/scorecard.png',
        'static/description/charts/serpentine.png',
        'static/description/charts/smoothedLine.png',
        'static/description/charts/spiral.png',
        'static/description/charts/stepLine.png',
        'static/description/charts/sunburst.png',
        'static/description/charts/tile.png',
        'static/description/charts/timeline.png',
        'static/description/charts/todo.png',
        'static/description/charts/tree.png',
        'static/description/charts/treemap.png',
        'static/description/charts/venn.png',
        'static/description/charts/voronoiTreemap.png',
        'static/description/charts/waterfall.png',
        'static/description/charts/wordCloud.png',
        'static/description/options/animation.png',
        'static/description/options/card_colors.png',
        'static/description/options/card_layouts.png',
        'static/description/options/cursor.png',
        'static/description/options/data_labels.png',
        'static/description/options/export.png',
        'static/description/options/funnel_direction.png',
        'static/description/options/grid.png',
        'static/description/options/legend.png',
        'static/description/options/list_layouts.png',
        'static/description/options/map_styles.png',
        'static/description/options/number_formats.png',
        'static/description/options/semi_circle.png',
        'static/description/options/stacked.png',
        'static/description/options/stacked_100.png',
        'static/description/options/targets.png',
        'static/description/options/themes.png',
        'static/description/options/tooltip.png',
        'static/description/options/zoom.png',
        'static/description/features/ai.png',
        'static/description/features/alerts.png',
        'static/description/features/bookmark.png',
        'static/description/features/builder.png',
        'static/description/features/company.png',
        'static/description/features/currency.png',
        'static/description/features/datasources.png',
        'static/description/features/demo.png',
        'static/description/features/drill.png',
        'static/description/features/email.png',
        'static/description/features/export.png',
        'static/description/features/filters.png',
        'static/description/features/import.png',
        'static/description/features/kpi.png',
        'static/description/features/menu.png',
        'static/description/features/query.png',
        'static/description/features/realtime.png',
        'static/description/features/rtl.png',
        'static/description/features/security.png',
        'static/description/features/share.png',
        'static/description/features/tv.png',
    
    
    ],
    'assets': {
        'web.assets_backend': [
            'dynamic_dashboard_ai_nexgen/static/src/css/dashboard.css',
            'dynamic_dashboard_ai_nexgen/static/src/css/query_builder.css',
            'dynamic_dashboard_ai_nexgen/static/src/css/iframe_mode.css',
            'dynamic_dashboard_ai_nexgen/static/src/utils/l10n.js',
            'dynamic_dashboard_ai_nexgen/static/src/utils/html2canvas_capture.js',
            'dynamic_dashboard_ai_nexgen/static/src/js/iframe_mode.js',
            'dynamic_dashboard_ai_nexgen/static/src/components/dashboard/render_scheduler.js',
            'dynamic_dashboard_ai_nexgen/static/src/components/dashboard/chart_engine.js',
            'dynamic_dashboard_ai_nexgen/static/src/components/dashboard/dashboard.js',
            'dynamic_dashboard_ai_nexgen/static/src/components/dashboard/dashboard.xml',
            'dynamic_dashboard_ai_nexgen/static/src/components/dashboard/dashboard_item.js',
            'dynamic_dashboard_ai_nexgen/static/src/components/dashboard/dashboard_item.xml',
            'dynamic_dashboard_ai_nexgen/static/src/components/dashboard/dashboard_item_preview.js',
            'dynamic_dashboard_ai_nexgen/static/src/components/dashboard/dashboard_item_type.js',
            'dynamic_dashboard_ai_nexgen/static/src/components/analysis/analysis_editor.js',
            'dynamic_dashboard_ai_nexgen/static/src/components/analysis/analysis_editor.xml',
            'dynamic_dashboard_ai_nexgen/static/src/components/query_builder/query_builder.js',
            'dynamic_dashboard_ai_nexgen/static/src/components/query_builder/query_builder.xml',
        ],
    },
    'post_init_hook': 'post_init_hook',
    'sequence': 1,
    'application': True,
    'installable': True,
    'auto_install': False,
}
