upstream odoo {
    server odoo:8019;
}
upstream odoo-chat {
    server odoo:8020;
}

server {
    listen 80;
    server_name _;

    # Certbot challenge
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name _;  # thay bằng domain thật: wujiatea.com

    ssl_certificate     /etc/letsencrypt/live/wujiatea.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/wujiatea.com/privkey.pem;

    proxy_read_timeout 720s;
    proxy_connect_timeout 720s;
    proxy_send_timeout 720s;

    # Longpolling
    location /websocket {
        proxy_pass http://odoo-chat;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        proxy_pass http://odoo;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_redirect off;

        # Buffer
        proxy_buffers 16 64k;
        proxy_buffer_size 128k;
    }

    # Tăng tốc static files
    location ~* /web/static/ {
        proxy_cache_valid 200 90m;
        proxy_buffering on;
        proxy_pass http://odoo;
        proxy_set_header Host $host;
    }

    gzip on;
    gzip_types text/css text/javascript application/json application/javascript;
}
