from . import test_pricing
from . import test_catalog_layout
from . import test_f5_nav_item
from . import test_f6_cart_submit
from . import test_g1_order_spacing
from . import test_g5_submit_confirm
from . import test_cart_feedback
from . import test_jv4_i18n
from . import test_jvr_badge
