{
    'name': 'Wujia Portal — Exam (Đào tạo / Thi)',
    'version': '19.0.3.0.0',
    'category': 'Wujia',
    'summary': 'Đăng ký thi nhượng quyền — backend khóa/kỳ thi + phiếu đa nhân sự + kết quả',
    'author': 'WujiaTea',
    'license': 'LGPL-3',
    'depends': ['wujia_portal_base', 'wujia_franchise', 'mail'],
    'data': [
        'security/wujia_exam_groups.xml',
        'security/ir.model.access.csv',
        'security/wujia_exam_rules.xml',
        'data/ir_sequence_data.xml',
        'views/backend_exam_time_slot_views.xml',
        'views/backend_exam_course_views.xml',
        'views/backend_exam_session_views.xml',
        'views/backend_exam_registration_views.xml',
        'views/backend_menu.xml',
        'views/sidenav_inherit.xml',
        'views/portal_exam.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'wujia_portal_exam/static/src/css/portal_exam.css',
            'wujia_portal_exam/static/src/js/portal_exam.js',
            'wujia_portal_exam/static/src/js/portal_exam_wizard.js',
        ],
    },
    'installable': True,
    'application': False,
    'auto_install': False,
}
