# -*- coding: utf-8 -*-
{
    'name': 'Wujia Franchise — Store Inspection (Khảo sát & Giám sát)',
    'version': '19.0.1.0.0',
    'category': 'Wujia',
    'summary': 'Phân hệ mở rộng quản lý khảo sát, giám sát cửa hàng, chấm điểm và đánh giá',
    'author': 'WujiaTea',
    'license': 'LGPL-3',
    'depends': [
        'wujia_franchise',
        'wujia_core',
        'contacts',
        'portal',
        'mail',
    ],
    'data': [
        'security/wujia_inspection_groups.xml',
        'security/ir.model.access.csv',
        'security/wujia_inspection_rules.xml',
        'data/inspection_grade_data.xml',
        'data/wujia_inspection_bootstrap.xml',
        'views/wujia_franchise_inspection_template_views.xml',
        'views/wujia_franchise_inspection_question_views.xml',
        'views/wujia_franchise_inspection_grade_views.xml',
        'views/wujia_franchise_inspection.xml',
        'views/wujia_franchise_inspection_report_templates.xml',
        'views/inspection_survey_web_templates.xml',
        'views/wujia_franchise_inspection_history_views.xml',
        'views/wujia_franchise_inspection_remediation_views.xml',
        'views/wujia_franchise_inspection_report_views.xml',
        'views/wujia_franchise_inspection_violation_views.xml',
        'views/wujia_franchise_needed_inspection_views.xml',
        'views/wujia_supervision_schedule_views.xml',
        'views/wujia_franchise_management_inspection_views.xml',
        'views/wujia_franchise_inspection_menu.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'wujia_franchise_inspection/static/src/css/wujia_inspection.css',
            'wujia_franchise_inspection/static/src/js/wujia_inspection_chart.js',
            'wujia_franchise_inspection/static/src/js/wujia_gps_field.js',
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
}
