{
    'name': 'Wujia Portal — Notification',
    'version': '19.0.2.9.0',
    'category': 'Wujia',
    'summary': 'Thông báo HQ → cửa hàng nhượng quyền (portal + quản trị backend)',
    'author': 'WujiaTea',
    'license': 'LGPL-3',
    'depends': ['wujia_portal_base', 'wujia_franchise', 'mail'],
    'data': [
        'security/wujia_notification_groups.xml',
        'security/ir.model.access.csv',
        'security/wujia_notification_rules.xml',
        'data/ir_sequence_data.xml',
        'data/notification_type_data.xml',
        'views/backend_notification_views.xml',
        'views/backend_menu.xml',
        'views/sidenav_inherit.xml',
        'views/header_bell_inherit.xml',
        'views/portal_notification.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'wujia_portal_notification/static/src/css/portal_notification.css',
            'wujia_portal_notification/static/src/js/header_bell_badge.js',
            'wujia_portal_notification/static/src/js/portal_notification_pc.js',
        ],
    },
    'installable': True,
    'application': False,
    'auto_install': False,
}
