# Copyright (C) NexGen Solutions
from . import l10n_utils
from . import constraints_utils
from . import dashboard_category
from . import dashboard
from . import dashboard_item
from . import res_config_settings
from . import ai_wizard
from . import dashboard_filter
from . import import_wizard
from . import dashboard_report
from . import dashboard_connection
from . import move_wizard
from . import dashboard_target
from . import dashboard_number_system
from . import dashboard_date_filter
from . import dashboard_item_source
from . import dashboard_mart
from . import dashboard_kpi
from . import dashboard_analysis
from . import dashboard_share
from . import demo_data
from . import demo_data_sources
from . import demo_business_apps
from . import dashboard_user_preference
